### PR TITLE
Add the `word-break` CSS property to _copy_computed_props so views with…

### PR DESCRIPTION
**Pull request by nelsonwong1012**
… `SC.AutoResize` will consider words that are longer than the view is wide and correctly calculate the height for that view.

### CODE REVIEW

**Comment by nelsonwong1012** [comment]
@mauritslamers Any chance I can entice you to take a look at this simple improvement?

**Comment by mauritslamers** [comment]
LGTM

**Comment by xogg** [comment]
@nelsonwong1012:
hi, am I correct that you have already tried to set the `shouldResizeHeight:true` on a view and it didn't worked out as desirable?

another question, what about a strictly one-liner views like Buttons, most of Menu Items, Select Views, etc.? will they change their behavior with this simple improvement?

**Comment by nelsonwong1012** [comment]
@xogg: Yes, I had `shouldResizeHeight: YES` on my view. I tried this on a 1 line menu item with long text and it had no effect. Haven't tested it thoroughly though. Since, `wordBreak` has to do with how content wraps to the next line, I feel like it should be copied. Same reasoning for `whiteSpace` and `wordWrap`, which are already in there.

**Pull request merged**
