### PR TITLE
Catch errors when accessing window.localStorage

### PR DESCRIPTION
**Pull request by jameschao**
There are some security related conditions that can throw an `Access denied` errors when accessing `window.localStorage`:
- https://mathiasbynens.be/notes/localstorage-pattern#comment-9
- http://stackoverflow.com/questions/13102116/access-denied-for-localstorage-in-ie10

We're actually seeing errors related to this from our application in production also.

So, I wanted to access `window.localStorage`in a try-catch block to prevent errors from being thrown unnecessarily.

### CODE REVIEW

**Comment by jameschao** [comment]
Hi @mauritslamers / @nicolasbadia - would you mind reviewing this? Thanks.

**Comment by mauritslamers** [comment]
Reviewing as we speak :)

**Comment by mauritslamers** [comment]
First of all: thank you for tracing this and your documentation makes the case extremely clear: SC is disregarding the Web Storage specification and consequently in error.

The only thing that bothers me with this fix is how such a case can be handled elegantly. If I would be in such a situation, I would like to give some descriptive error message to my users, for example that their security settings prevent the use of the application. Please correct me if you think I am wrong, wouldn't the use of SC.Logger.error() possibly cause the error to happen silently?

**Comment by jameschao** [comment]
Hi @mauritslamers, thanks for the feedback.

From what I understand of `SC.UserDefaults` (which isn't to much), it seems to me like the error case is something that application should take care of. For example, in my app it's okay to fail silently, though it might not be for other apps. Since this is an application-specific behavior, and quite low level, I think using `SC.Logger.error` is appropriate since it does displays in the browser console and yet not fail too "loudly" (in case the app developer doesn't want that).

The code actually already provides a way for the app to provide a delegate provide defaults and such (https://github.com/sproutcore/sproutcore/blob/master/frameworks/foundation/system/user_defaults.js#L117-L121), so potentially the app can do some handling there too to message the user?

**Comment by mauritslamers** [comment]
Using the delegate itself is indeed a good idea. It turns out however there is no such delegate defined anywhere (whoops?). Would you be so kind to do the following:

* add a file to https://github.com/sproutcore/sproutcore/tree/master/frameworks/foundation/delegates in which you describe the delegate interface. 
* add to this interface the empty functions 
  * userDefaultsNeedsDefault(userDefaults, keyName, userKeyName)
  * userDefaultsDidChange(userDefaults, keyName, value, userKeyName)
  * userDefaultsDidError(userDefaults, keyName, value, userKeyName)

and in the original file add a line like 

`if (del && del.userDefaultsDidError) del.userDefaultsDidError(this, keyName, value, userKeyName);`

to the catch blocks.

Could you please also add a line to the CHANGES.md file in the root in which you describe the change? Something like "Fix for an uncaught error in SC.UserDefaults and adding a definition and extension of SC.UserDefaultsDelegate".

**Comment by jameschao** [comment]
OK, updated based on your suggestions @mauritslamers.

**Comment by mauritslamers** [comment]
@jameschao Thanks a lot for your contribution!

**Comment by mauritslamers** [comment]
I also added these changes to the 1-11-stable branch.

**Pull request merged**
