### PR TITLE
Removes the keypress handler which has no listener and is not used anymore

### PR DESCRIPTION
**Pull request by nicolasbadia**
Also removes a Firefox keypress hack which is not needed anymore in recents version of Firefox and is
breaking copy/paste shortcut in text fields.

### CODE REVIEW

**Comment by mauritslamers** [comment]
Looks good to me. If @mirion also agrees, I will merge the PR.

**Comment by nicolasbadia** [comment]
Wait before merging this, it looks like I miss something... I will review this soon.

**Comment by mauritslamers** [comment]
Any progress?

**Comment by nicolasbadia** [comment]
Replaced by https://github.com/sproutcore/sproutcore/pull/1365

**Pull request closed without merging**
