### PR TITLE
Adds a recordType computed property to SC.Record

### PR DESCRIPTION
**Pull request by nicolasbadia**

### CODE REVIEW

**Comment by nicolasbadia** [comment]
This is causing issue with `propagateToAggregates` because the `recordType` property return a wrong value.

**Comment by nicolasbadia** [comment]
Should now be safe to merge.

**Comment by mauritslamers** [comment]
I think this is better implemented differently. The reason is that every object in JS is already carrying around a reference to its constructor (in our case an extended SC.Record class). So, you could simply do:

```
  recordType: function () {
    return this.constructor;
  }.property().cacheable()
```

And as far as I can see you should get the same result.

**Comment by nicolasbadia** [comment]
This is indeed the way to go! I will make the changes...

**Comment by nicolasbadia** [comment]
Closed by https://github.com/sproutcore/sproutcore/pull/1410

**Pull request closed without merging**
