### PR TITLE
Added a cachedViewLimit property to SC.ContainerView

### PR DESCRIPTION
**Pull request by nicolasbadia**
See https://github.com/sproutcore/sproutcore/issues/1027

### CODE REVIEW

**Comment by mauritslamers** [comment]
@nicolasbadia Is it possible to make a separate PR for the memory leak fix? As the cachedViewLimit API needs a more thorough review, it would be not very useful to have this fix wait for much longer...

**Comment by nicolasbadia** [comment]
Has you may have seen, the memory leak fix can't be pick without the cacheViewLimit commit.
I would have to rewrite it and pick some unit tests from the cacheViewLimit commit. Not that it is very complicated, but before I do that, I wanted to discuss the issues with the cachedViewLimit API.

I initially started to add a property to define if all the views should be cache or not. Tyler then suggest me to replace it with a cacheViewLimit which would add control on how many view should be cache.

How do you think we could enhance it ?

Personally, I think we should keep it like it but make the 0 value cache everything, while 1 would only cache the current view (which mean no cache), and 2 would cache the current one and the last one... 
I would also keep the default value of cacheViewLimit to 0 to make SC.ContainerView cache everything by default.

Thoughts ?

**Comment by mauritslamers** [comment]
@nicolasbadia I obviously didn't read the descriptions above well. Sorry for that.
I agree with @dcporter that the solution in this PR is a bit blunt, mainly because there is no way to indicate which view will be cached. 

I see essentially two approaches, which are equivalent to either a blacklist or a whitelist: either everything is cached by default, and it is indicated which views should not be cached, or nothing is cached by default and it is indicated which views should be cached.
If I understand things correctly, the current situation is that everything is cached by default. 

My idea is that it would be best to give a developer a fine grained control over what is being cached and what not. 

One solution could be that the caching inside a container view could be determined by a property on the contained view, instead of a setting on the container view. If the default is that everything is cached, then a containerViewShouldNotCache property could be set to true. I am not sure this property should be defined on the SC.View class.

Another solution could be that a list is defined on the container view of which views need to be cached (or which not) by adding a list with paths to be cached, or not to be cached.

**Comment by nicolasbadia** [comment]
Just fount a branch which were already adding a caching option 5 years ago... https://github.com/sproutcore/sproutcore/commit/2dca84e6f99bd50829dd1fa04a5f9bbee1863b1d

Like this commit, I think a simple `cacheViews` property would be enough.

**Comment by nicolasbadia** [comment]
Closed in favor of https://github.com/sproutcore/sproutcore/pull/1439

**Pull request closed without merging**
