### PR TITLE
Call sc_super() in readError() if autonomous nested store

### PR DESCRIPTION
**Pull request by dstevick41**
Errors generated on autonomous nested stores are retained in the nested
store itself.  readError() therefore should consult this error list
instead of the parentStore’s error list if the nested store is
autonomous.

### CODE REVIEW

**Comment by mauritslamers** [comment]
Looks good to me, though I wonder whether there should be a test case.

**Comment by mauritslamers** [comment]
@nicolasbadia @mirion Please your comments

**Comment by nicolasbadia** [comment]
Ok for me too. But I'm wondering if we shouldn't do the same thing with `readQueryError` and maybe other methods...

**Comment by mauritslamers** [comment]
@nicolasbadia I think that would be clever. @dstevick41 Would you be able to add this to the readQueryError as well and perhaps other methods needing this?

**Comment by dstevick41** [comment]
Hi @mauritslamers, I would be glad to look at the other methods.  Should I do another pull request for those changes or can I add it this this one?

**Comment by mauritslamers** [comment]
@dstevick41 You can add it to this one, better have the fixes together. Thanks in advance!

**Comment by dstevick41** [comment]
I made the change to readQueryError() but I'm still looking at retrieveRecords(), queryFor(), refreshQuery(), discardChanges() and reset().  I will need to runs specific tests to see if they are doing the right thing on Autonomous Nested Stores.

**Comment by mauritslamers** [comment]
@dstevick41 The best way to figure that out is to extend the current tests to include your problem. You will know immediately which methods to change.

**Comment by dstevick41** [comment]
Great suggestion @mauritslamers.  I found the tests and I'm looking at them now.

**Comment by dstevick41** [comment]
I made the same change to readQueryError() that I made to readError() so that it uses the base class method instead of the parent store for cases of autonomous nested stores.
Added a new test case file autonomous_errorMethods.js that parallels the error_methods.js tests for the regular store.
Checked several other nested_store methods to see if they required the same change.  I did not find any others.

**Comment by dstevick41** [comment]
Hi @mauritslamers,  I believe I'm done with this now.

**Comment by mauritslamers** [comment]
@dstevick41 Great work. Thanks a lot for your contribution!

**Comment by mauritslamers** [comment]
@dstevick41 One question: could you also do an edit of CHANGES.LOG in this PR describing the fix?

**Comment by dstevick41** [comment]
Hi @mauritslamers, sure thing.  Where do I find the CHANGES.LOG?

**Comment by mauritslamers** [comment]
@dstevick41 try the one in the root of the project :)

**Comment by dstevick41** [comment]
Thanks @mauritslamers.  The updates are now in the change log.

**Comment by nicolasbadia** [comment]
@dstevick41 I guess you forgot to push the change log commit to github because I can't find it. Can you do it so I can merge that. Thanks for your work by the way :-)

**Comment by dstevick41** [comment]
Hi @nicolasbadia, I see the commit in the change request now (5th one down on 23 May).  Looks like I may have forgotten to do a sync.  Please let me know if you don't see it.

**Comment by nicolasbadia** [comment]
Merged. Thanks

**Pull request closed without merging**
