### PR TITLE
Fixes 1318

### PR DESCRIPTION
**Pull request by rcatalano**
SC.View#viewFor now bails if the element is an instance of HTMLDocument.

### CODE REVIEW

**Comment by nicolasbadia** [comment]
Not sure if this should be check there or in `targetViewForEvent` but, it definitely need to be fixed.

**Comment by nicolasbadia** [comment]
This is breaking IE <= 10. 
Do you remember what was the point of this fix ?

**Comment by nicolasbadia** [comment]
For the record, it breaks because HTMLDocument were only added in internet explorer 11.

**Comment by nicolasbadia** [comment]
Well to answer my previous question, the point this fix is explain in #1318... as the title say.

So I dig a little more into this, and I found out that when you drag an element out of the browser window, Firefox set the event target to an instance of `Document` (or `HTMLDocument`) while the other browsers (Chrome, Safari, IE) set it to the html main element (`document.documentElement`).

To fix this, I suggest that we stop the event directly in the `mousemove` handler if the event target is not an instance of `Element` like this:

    mousemove: function(evt) {
      if (!(evt.target instanceof Element)) return;
      ...

**Comment by mauritslamers** [comment]
I agree with @nicolasbadia. I have been searching for some documentation on the reason of this difference, but couldn't find anything.

**Comment by mauritslamers** [comment]
@nicolasbadia could you make a new PR for this?

**Comment by nicolasbadia** [comment]
Done :-)

**Pull request closed without merging**
