### PR TITLE
Prevents views from being resize when they are orphaned

### PR DESCRIPTION
**Pull request by nicolasbadia**
This is fixing https://github.com/sproutcore/sproutcore/issues/1020 and https://github.com/sproutcore/sproutcore/pull/1321.

### CODE REVIEW

**Comment by mauritslamers** [comment]
Interesting issue. Can you be more specific on what you think the `_orphaned` override was originally supposed to do, and consequently why it deserves to be taken out?

**Comment by nicolasbadia** [comment]
I actually have no idea... Tyler wasn't able to tell me why in #1020. I just know it cause trouble and I wrote unit tests to prove it.

**Comment by nicolasbadia** [comment]
@mauritslamers Can we merge this ?

**Comment by mauritslamers** [comment]
yes we can!

**Pull request merged**
